on:
  push:
    branches:
    - main
jobs:
  deploy-global-commands:
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_PROD }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID_PROD }}
      DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID_PROD }}
    name: deploy coomands to prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: npm install and build
        run: |
          npm ci 
          npm run build --workspaces --if-present
          
      - name: deploy commands
        run: npm run start -w rok_command_deployment
